version: '3'

services:
  small-redis:
    image: redis
    command: redis-server --requirepass REDISPASSWORD
    environment:
      - REDIS_USER=REDISPASSWORD
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data # Maps ./redis-data on the host to /data in the container

  neo4j:
    image: neo4j:5.22.0-community
    ports:
      - "7475:7474"
      - "7688:7687"
    environment:
      - NEO4J_AUTH=neo4j/NEO4JPASSWORD
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_PLUGINS=["apoc","apoc-extended","graph-data-science"]
    volumes:
      - ./neo4j-data:/data # Maps ./neo4j-data on the host to /data in the container
      - ./neo4j_import:/var/lib/neo4j/import
      - ./neo4j_plugins:/plugins

  mongo:
    image: mongo
    ports:
      - "27018:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=MONGOPASSWORD
      - MONGO_INITDB_ROOT_PASSWORD=MONGOPASSWORD
    volumes:
      - ./mongo-data:/data/db # Maps ./mongo-data on the host to /data/db in the container


